### ISSUE TITLE
Add AWS dashboard to measure account creation

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-address-server#33]

**Comment by oed** [comment]
@c-castillo something like that. How many users are registered I think.

**Comment by c-castillo** [comment]
Thanks @oed for the clarification. I think in this case the users are measured by the number of rootStores created (not by address, since you can add N devices to your 3Box)

**Comment by oed** [comment]
Yes, precisely 👍🏻

**Comment by c-castillo** [comment]
@msena @oed @dazuck 
The WIP dashboard is located at
https://datastudio.google.com/open/1lrhZVm3o5LvSvGadibqozMbwWQhP7bIE

**Comment by michaelsena** [comment]
@c-castillo it's not letting me open the link, can you add our emails directly to the dashboard from data studio. I dont think we have permission
