### ISSUE TITLE
Make Google Data Studio dashboards with warehouse data

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-address-server#41]
We would like to know user count, and other visualizations of the metrics we spec'ed.

**Comment by michaelsena** [comment]
@oed and @c-castillo picking up the conversations from boxcon - it would be great to have greater detail into server metrics. @oed which metrics did you want to see?

**Comment by oed** [comment]
I think we wanted to create a general dashboard for all of our servers and not just the address-server, so it might make sense to move this story.
From the address-server I'd like to see:
* Number of unique users (links from eth-address to muport-did
* Number of non public users (links from muport-did to odb-address), this should be a slightly larger superset to the above

**Comment by michaelsena** [comment]
@c-castillo when do you think we will be ready with the pipeline for me to begin creating the dashboards? Your stories are blocking me here and I want to ensure I have enough time to still get this done, while not forcing myself to stay up tomorrow night to squeeze it in

**Comment by c-castillo** [comment]
@michaelsena most likely tomorrow(tuesday) during the morning. I'm fixing an issue because I need to modify the pipeline to create timeseries instead of counters.

**Comment by dazuck** [comment]
@michaelsena these mostly aren't super relevant in this first pass, but worth a quick scan anyway as we should over time keep iterating on business-level dashboard of the key metrics (beyond just product) - https://a16z.com/2015/08/21/16-metrics/

**Comment by michaelsena** [comment]
closing, stale
