### ISSUE TITLE
Add support for verifying eip1271 signatures

### ISSUE THREAD

**Issue by oed** [3box/3box-address-server#60]
Similar to how eip1271 signature verification is added to 3box-js in https://github.com/3box/3box-js/issues/583 we add the same functionality of verifying these signatures to the address-server. The main difference here is that we need to provide an internal ethereum-rpc provider, like infura.

**Comment by michaelsena** [comment]
@zachferland we didn't get to this today, do you think we can get to it tomorrow, or should @oed help here?
