### ISSUE TITLE
Add and configure dev/master staging/production environments

### ISSUE THREAD

**Issue by zachferland** [3box/3box-address-server#87]
Of course important to have both for testing and build/test pipelines, but also more important not that did are resolve from ipfs blockstore. This means and staging/production of the pinning node can no longer share an address server, each need to reference own staging/production instances. There is a number of steps to have two separate deployments. 

- Split branches, dev and master
       - master used a while ago, simply overwrite to have master reflect current dev (all releases have been there right now)
- add dev postgres instance (could still be shared in first iteration)
- Modify and secrets(kms)/configs for both env 
- point domain to master stage service (instead develop)
- (not required now) add domain for master service (intention to eventually phase out current), have one for dev as well

**Comment by oed** [comment]
This makes me think. Do we need a develop p2p.3box.io for the websocket star as well?

**Comment by msterle** [comment]
@oed yes, I think we should have an entirely self-contained dev environment. Does this relate specifically to the address server, though, or should we handle it in a different epic?

**Comment by msterle** [comment]
also fixes #86

**Comment by oed** [comment]
No it doesn't relate to the address-server.
